#+TITLE: btprnt
=btprnt= is a 1-bit graphics library.

These are some (very) brief words on how to use it inside
LIL.

A new btprnt instance is created with =bpnew=.

To create a 256x128 btprnt instance stored to sndkit
dictionary value "bp":

#+BEGIN_SRC lil
bpnew bp 256 128
#+END_SRC

btprnt draws to regions, or subsections of the entire
bitmap canvas. LIL doesn't have garbage collection, nor
does it have the greatest data structures, so the
strategy taken here is to use a pre-allocated set of
regions accessible by index. There are 16 pre-allocated
regions to choose frome.

=bpset= sets a region at an index to a specific area:

bpset: bp index x y w h

This sets region 0 to be the entire canvas:

#+BEGIN_SRC lil
bpset [grab bp] 0 0 0 256 128
#+END_SRC


=bpget= retrieves a region stored at a particular index.

bpget: bp, index

As a small example, this lil program creates an instance
of btprnt, generates a rectangle, and writes it to a pbm
file:

#+BEGIN_SRC lil
bpnew bp 256 128
bpset [grab bp] 0 0 0 256 128
bprect [bpget [grab bp] 0] 10 10 64 64 1
bppbm [grab bp] out.pbm
#+END_SRC

=bpmrk=, =bpclr=, and =bpnxt= are mark, clear, and
next operations for regions in the pool. Mark will set
a region in the region pool to be used. clear will clear
that bit. Next, will return the next available free
register. Using these together can be a way to abstract
away region ID.

#+BEGIN_SRC lil
set $reg [bpnxt [grab bp]]
bgmrk [grab bp] $reg
bgclr [grab bp] $reg
#+END_SRC

=bppbm= generates a PBM file from a btprnt canvas:

#+BEGIN_SRC lil
bppbm [grab bp] "out.pbm"
#+END_SRC

=bprect= draws a location at (x,y) with dimensions (w, h)

#+BEGIN_SRC lil
bprect [bpget [grab bp] 0] x y w h
#+END_SRC

=bprectf= draws a filled rectangle:

#+BEGIN_SRC lil
bprectf [bpget [grab bp] 0] x y w h
#+END_SRC

=bptr= transfers a btprnt canvas to a
@!(ref "gfxbuf")!@ instance. TODO: explain more.

#+BEGIN_SRC lil
bptr [grab bp] x y w h xoff yoff clr
#+END_SRC

=bpfill= fills a region. color: 0 is white, 1 is black.

#+BEGIN_SRC lil
bpfill [bpget [grab bp] 0] color
#+END_SRC

=bpcirc= draws a circle.

#+BEGIN_SRC lil
bpcirc [bpget [grab bp] 0] cx cy r clr
#+END_SRC

Other words: =bpfnt_default=, =bptxtbox=, =bpchar=,
=bpline=.

I ran out of time, I'll need to document
these later. check the source code (lib/btprnt/l_btprnt.c).

=bpoutline= draws an outline around a region. It is one
of the layout commands. =clr= will determine the outline
color.

#+BEGIN_SRC lil
bpoutline [bpget [grab bp] 0] clr
#+END_SRC

To draw a rounded rectangle, use =bproundrect=.

#+BEGIN_SRC lil
bproundrect [bpget [grab bp] 0] 0 0 50 50 10
#+END_SRC

Fonts, text:

#+BEGIN_SRC lil
bpfnt_default fnt
bptxtbox [bpget [grab bp] 0] 0 0 hello
#+END_SRC
