CFLAGS+=-Ilib/sndkit
CFLAGS+=-Ilib/sndkit/nodes
CFLAGS+=-Ilib/sndkit/dsp
OBJ +=\
lib/sndkit/core.o \
lib/sndkit/dsp/dcblocker.o \
lib/sndkit/dsp/env.o \
lib/sndkit/dsp/metro.o \
lib/sndkit/dsp/modalres.o \
lib/sndkit/dsp/osc.o \
lib/sndkit/dsp/scale.o \
lib/sndkit/dsp/rline.o \
lib/sndkit/dsp/peakeq.o \
lib/sndkit/dsp/blep.o \
lib/sndkit/dsp/glottis.o \
lib/sndkit/dsp/rephasor.o \
lib/sndkit/dsp/bitosc.o \
lib/sndkit/dsp/phasewarp.o \
lib/sndkit/dsp/vardelay.o \
lib/sndkit/dsp/expon.o \
lib/sndkit/dsp/tract.o \
lib/sndkit/dsp/phasor.o \
lib/sndkit/dsp/smoother.o \
lib/sndkit/dsp/bigverb.o \
lib/sndkit/dsp/gen.o \
lib/sndkit/dsp/mtof.o \
lib/sndkit/dsp/phsclk.o \
lib/sndkit/lil/lil_main.o \
lib/sndkit/lil/lil.c99 \
lib/sndkit/nodes/chorus/chorus.o \
lib/sndkit/nodes/chorus/l_chorus.o \
lib/sndkit/nodes/biramp/l_biramp.o \
lib/sndkit/nodes/biramp/biramp.o \
lib/sndkit/nodes/chaosnoise/chaosnoise.o \
lib/sndkit/nodes/chaosnoise/l_chaosnoise.o \
lib/sndkit/nodes/rline/rline.o \
lib/sndkit/nodes/rline/l_rline.o \
lib/sndkit/nodes/blep/blep.o \
lib/sndkit/nodes/blep/l_blep.o \
lib/sndkit/nodes/valp1/valp1.o \
lib/sndkit/nodes/valp1/l_valp1.o \
lib/sndkit/nodes/reg/reg.o \
lib/sndkit/nodes/bezier/l_bezier.o \
lib/sndkit/nodes/bezier/bezier.o \
lib/sndkit/nodes/bitnoise/bitnoise.o \
lib/sndkit/nodes/bitnoise/l_bitnoise.o \
lib/sndkit/nodes/phsclk/l_phsclk.o \
lib/sndkit/nodes/phsclk/phsclk.o \
lib/sndkit/nodes/scale/scale.o \
lib/sndkit/nodes/scale/l_scale.o \
lib/sndkit/nodes/env/env.o \
lib/sndkit/nodes/env/l_env.o \
lib/sndkit/nodes/phasewarp/phasewarp.o \
lib/sndkit/nodes/phasewarp/l_phasewarp.o \
lib/sndkit/nodes/loader.o \
lib/sndkit/nodes/expon/expon.o \
lib/sndkit/nodes/expon/l_expon.o \
lib/sndkit/nodes/sine/sine.o \
lib/sndkit/nodes/sine/l_sine.o \
lib/sndkit/nodes/peakeq/peakeq.o \
lib/sndkit/nodes/peakeq/l_peakeq.o \
lib/sndkit/nodes/tract/l_tract.o \
lib/sndkit/nodes/tract/tract.o \
lib/sndkit/nodes/bitosc/l_bitosc.o \
lib/sndkit/nodes/bitosc/bitosc.o \
lib/sndkit/nodes/sklil.c99 \
lib/sndkit/nodes/glottis/l_glottis.o \
lib/sndkit/nodes/glottis/glottis.o \
lib/sndkit/nodes/dcblocker/dcblocker.o \
lib/sndkit/nodes/dcblocker/l_dcblocker.o \
lib/sndkit/nodes/smoother/l_smoother.o \
lib/sndkit/nodes/smoother/smoother.o \
lib/sndkit/nodes/rephasor/l_rephasor.o \
lib/sndkit/nodes/rephasor/rephasor.o \
lib/sndkit/nodes/expmap/expmap.o \
lib/sndkit/nodes/expmap/l_expmap.o \
lib/sndkit/nodes/fmpair/l_fmpair.o \
lib/sndkit/nodes/fmpair/fmpair.o \
lib/sndkit/nodes/wav/l_wavout.o \
lib/sndkit/nodes/wav/wavin.o \
lib/sndkit/nodes/wav/l_wavin.o \
lib/sndkit/nodes/wav/wavout.o \
lib/sndkit/nodes/modalres/modalres.o \
lib/sndkit/nodes/modalres/l_modalres.o \
lib/sndkit/nodes/buffer/buffer.o \
lib/sndkit/nodes/oscf/l_oscf.o \
lib/sndkit/nodes/oscf/oscf.o \
lib/sndkit/nodes/tabnew/tabnew.o \
lib/sndkit/nodes/osc/l_osc.o \
lib/sndkit/nodes/osc/osc.o \
lib/sndkit/nodes/phasor/l_phasor.o \
lib/sndkit/nodes/phasor/phasor.o \
lib/sndkit/nodes/metro/metro.o \
lib/sndkit/nodes/metro/l_metro.o \
lib/sndkit/nodes/vardelay/l_vardelay.o \
lib/sndkit/nodes/vardelay/vardelay.o \
lib/sndkit/nodes/arith/l_arith.o \
lib/sndkit/nodes/arith/arith.o \
lib/sndkit/nodes/mtof/l_mtof.o \
lib/sndkit/nodes/mtof/mtof.o \
lib/sndkit/nodes/bigverb/l_bigverb.o \
lib/sndkit/nodes/bigverb/bigverb.o \
lib/sndkit/nodes/gen/l_gen.o \
lib/sndkit/nodes/gen/gen.o \
lib/sndkit/dsp/vowel.o \
lib/sndkit/nodes/vowel/vowel.o \
lib/sndkit/nodes/vowel/l_vowel.o \
lib/sndkit/dsp/vowshape.o \
lib/sndkit/dsp/clkphs.o \
lib/sndkit/nodes/clkphs/clkphs.o \
lib/sndkit/nodes/clkphs/l_clkphs.o \
lib/sndkit/nodes/cable/l_cable.o \
lib/sndkit/nodes/cable/cabnew.o \
lib/sndkit/dsp/noise.o \
lib/sndkit/nodes/noise/l_noise.o \
lib/sndkit/nodes/noise/noise.o \
lib/sndkit/nodes/butterworth/l_butterworth.o \
lib/sndkit/nodes/butterworth/butterworth.o \
lib/sndkit/dsp/butterworth.o \
lib/sndkit/nodes/sparse/l_sparse.o \
lib/sndkit/nodes/sparse/sparse.o \
lib/sndkit/dsp/sparse.o \
lib/sndkit/nodes/softclip/l_softclip.o \
lib/sndkit/nodes/softclip/softclip.o \
lib/sndkit/dsp/softclip.o \
lib/sndkit/dsp/fmpair.o \
lib/sndkit/dsp/tseq.o \
lib/sndkit/nodes/tseq/tseq.o \
lib/sndkit/nodes/tseq/l_tseq.o \
lib/sndkit/dsp/thresh.o \
lib/sndkit/nodes/thresh/thresh.o \
lib/sndkit/nodes/thresh/l_thresh.o \
lib/sndkit/dsp/oscf.o \
lib/sndkit/dsp/expmap.o \
lib/sndkit/dsp/bitnoise.o \
lib/sndkit/dsp/bezier.o \
lib/sndkit/dsp/valp1.o \
lib/sndkit/dsp/chaosnoise.o \
lib/sndkit/dsp/biramp.o \
lib/sndkit/dsp/chorus.o \
lib/sndkit/extra/verbity/verbity.o \
lib/sndkit/extra/verbity/l_verbity.o \
lib/sndkit/extra/loader.o \
lib/sndkit/extra/talkbox/talkbox.o \
lib/sndkit/extra/talkbox/l_talkbox.o \
lib/sndkit/extra/padsynth/padsynth.o \
lib/sndkit/extra/padsynth/l_padsynth.o \
lib/sndkit/extra/mags/mags.o \
lib/sndkit/extra/mags/l_mags.o \
lib/sndkit/extra/kissfft/kiss_fft.o \
lib/sndkit/extra/kissfft/kiss_fftr.o \
lib/sndkit/dsp/adsr.o \
lib/sndkit/nodes/adsr/adsr.o \
lib/sndkit/nodes/adsr/l_adsr.o \
lib/sndkit/dsp/tenv.o \
lib/sndkit/nodes/tenv/tenv.o \
lib/sndkit/nodes/tenv/l_tenv.o \
lib/sndkit/nodes/tick/tick.o \
lib/sndkit/nodes/tick/l_tick.o \
lib/sndkit/extra/verify/l_verify.o \
lib/sndkit/extra/verify/verify.o \
lib/sndkit/extra/verify/md5.o \
lib/sndkit/dsp/tgate.o \
lib/sndkit/nodes/tgate/tgate.o \
lib/sndkit/nodes/tgate/l_tgate.o \
lib/sndkit/dsp/dblin.o \
lib/sndkit/nodes/dblin/dblin.o \
lib/sndkit/nodes/dblin/l_dblin.o \

# graforge embedded in sndkit is now the standard
OBJ += lib/sndkit/graforge/graforge.o
