OBJ+=lib/sqlite3/sqlite3.o
OBJ+=lib/sqlite3/shell.c99
CFLAGS+=-DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_JSON1

# recommended SQLite build flags for CLI
CFLAGS+=-DSQLITE_THREADSAFE=0
CFLAGS+=-DSQLITE_ENABLE_EXPLAIN_COMMENTS
# CFLAGS+=-DSQLITE_HAVE_ZLIB
CFLAGS+=-DSQLITE_INTROSPECTION_PRAGMAS
CFLAGS+=-DSQLITE_ENABLE_UNKNOWN_SQL_FUNCTION
CFLAGS+=-DSQLITE_ENABLE_STMTVTAB
CFLAGS+=-DSQLITE_ENABLE_DBPAGE_VTAB
CFLAGS+=-DSQLITE_ENABLE_DBSTAT_VTAB
CFLAGS+=-DSQLITE_ENABLE_OFFSET_SQL_FUNC
CFLAGS+=-DSQLITE_ENABLE_RTREE
CFLAGS+=-DSQLITE_ENABLE_FTS4

ifdef USE_READLINE
CFLAGS+=-DHAVE_READLINE=1
endif

