#+TITLE: in-memory operations for gestvm
* Overview
This implements some operations and structures that allow
UXN code to be assembled to blocks of memory, rather than
a file. This allows for better integration with the mnolth
ecosystem.
* Tangled File
Probably called =memops.c=. No header file required, since
the only external functions here will the loaders.

#+NAME: memops.c
#+BEGIN_SRC c :tangle lib/gestvm/memops.c
#include <stdlib.h>
#include <string.h>
#include "sndkit/graforge/graforge.h"
#include "sndkit/core.h"
#include "sndkit/lil/lil.h"
#include "sndkit/nodes/sklil.h"
#include "lua/lua.h"
#include "lua/lauxlib.h"
#include "uxn/uxn.h"

/* TODO: don't use GESTVM_PRIV */
#define GESTVM_PRIV
#include "gestvm.h"

<<typedefs>>
<<funcdefs>>
<<static_funcdefs>>
<<funcs>>
#+END_SRC
* Lua and LIL loaders
Called =gestvm_memops_lil= and =gestvm_memops_lua=.

#+NAME: funcdefs
#+BEGIN_SRC c
void gestvm_memops_lua(lua_State *L);
void gestvm_memops_lil(lil_t lil);
#+END_SRC

#+NAME: funcs
#+BEGIN_SRC c
void gestvm_memops_lua(lua_State *L)
{
    lua_register(L, "gestvm_compile", gestvm_compile);
    lua_register(L, "gestvm_last_values", gestvm_last_values);
}
#+END_SRC

#+NAME: funcs
#+BEGIN_SRC c
void gestvm_memops_lil(lil_t lil)
{
    <<lil_entries>>
}
#+END_SRC

* Core C component
This will outline the core structure in C, and the basic
operations required to set and get memory buffers into it.

#+NAME: typedefs
#+BEGIN_SRC c
typedef struct {
    unsigned char *buf;
    size_t size;
} gestvm_membuf;
#+END_SRC
* Creating a new memory file (LIL: gmemnew)
This is the component that creates a new instance of the
file that automatically cleans itself up when it is
released.

#+NAME: lil_entries
#+BEGIN_SRC: c
lil_register(lil, "gmemnew", l_gmemnew);
#+END_SRC

#+NAME: static_funcdefs
#+BEGIN_SRC c
static lil_value_t l_gmemnew(lil_t lil,
                             size_t argc,
                             lil_value_t *argv);
#+END_SRC

#+NAME: funcs
#+BEGIN_SRC c
static void membuf_clean(void *ptr)
{
    gestvm_membuf *mem;
    mem = ptr;
    free(mem->buf);
    free(mem);
}

static lil_value_t l_gmemnew(lil_t lil,
                             size_t argc,
                             lil_value_t *argv)
{
    int rc;
    const char *key;
    gestvm_membuf *mem;
    sk_core *core;

    SKLIL_ARITY_CHECK(lil, "gmemnew", argc, 1);

    core = lil_get_data(lil);

    key = lil_to_string(argv[0]);
    mem = malloc(sizeof(gestvm_membuf));
    mem->buf = NULL;
    mem->size = 0;

    rc = sk_core_append(core,
                        key,
                        strlen(key),
                        mem,
                        membuf_clean);

    SKLIL_ERROR_CHECK(lil, rc, "gmemnew didn't work out.");

    return NULL;
}
#+END_SRC
* Symbol lookup (LIL: gmemsym)
Mimics the same logic as found in =gestvmsym=, except with

#+NAME: lil_entries
#+BEGIN_SRC: c
lil_register(lil, "gmemsym", l_gmemsym);
#+END_SRC

For now, this is a very quick hack of the lookup code
found in gestvm. Read is still done like the file
handler version with fread to minimize code changes.

#+NAME: static_funcdefs
#+BEGIN_SRC c
static unsigned int lookup(gestvm_membuf *rom, const char *sym);
#+END_SRC

#+NAME: funcs
#+BEGIN_SRC c
static void not_fread(void *ptr,
                      int sz,
                      gestvm_membuf *mem,
                      int *pos)
{
    int i;
    unsigned char *m;

    m = ptr;
    for (i = 0; i < sz; i++) {
        if (*pos >= mem->size) return;
        m[i] = mem->buf[*pos];
        *pos = (*pos) + 1;
    }
}

static unsigned int lookup(gestvm_membuf *rom, const char *sym)
{
    unsigned char symlen;
    unsigned short sz;
    unsigned char buf[64];
    unsigned int addr;
    int pos;

    symlen = strlen(sym);
    addr = 0;

    memset(buf, 0, 64);

    pos = 0;
    not_fread(buf, 3, rom, &pos);

    if (buf[0] != 'S' || buf[1] != 'Y' || buf[2] != 'M') {
        return 0;
    }

    sz = 0;
    not_fread(buf, 2, rom, &pos);

    sz = buf[0] + (buf[1] << 8);

    while (sz) {
        unsigned char len;
        len = 0;
        not_fread(&len, 1, rom, &pos);

        if (len == symlen) {
            int i;
            int match;
            not_fread(buf, len, rom, &pos);
            match = 1;
            for (i = 0; i < len; i++) {
                if (buf[i] != sym[i]) {
                    match = 0;
                    break;
                }
            }

            if (match) {
                not_fread(buf, 2, rom, &pos);
                addr = buf[0] + (buf[1] << 8);
                break;
            } else {
                pos += 2;
            }
        } else {
            pos += len + 2;
        }

        sz -= (len + 2 + 1);
    }

    return addr;
}
#+END_SRC

#+NAME: static_funcdefs
#+BEGIN_SRC c
static lil_value_t l_gmemsym(lil_t lil,
                             size_t argc,
                             lil_value_t *argv);
#+END_SRC

#+NAME: funcs
#+BEGIN_SRC c
static lil_value_t l_gmemsym(lil_t lil,
                             size_t argc,
                             lil_value_t *argv)
{
    const char *sym;
    unsigned int addr;
    int rc;
    gestvm_membuf *mem;
    void *ud;
    sk_core *core;

    SKLIL_ARITY_CHECK(lil, "gestvmsym", argc, 2);

    core = lil_get_data(lil);
    rc = sk_core_generic_pop(core, &ud);

    SKLIL_ERROR_CHECK(lil, rc, "could not get memory");

    mem = ud;

    sym = lil_to_string(argv[1]);

    addr = lookup(mem, sym);

    SKLIL_ERROR_CHECK(lil, (addr == 0), "Problem finding symbol");

    return lil_alloc_integer(addr);
}
#+END_SRC

a buffer instead of a file.
* uxntal compilation (Lua: gestvm_compile)
In charge of compiling TAL code to a uxn bytecode, which
is written to a buffer. This is then saved to the
memory buffer instance managed by sndkit. It is assumed
that the dynamically allocated memory will be properly
freed later.

#+NAME: static_funcdefs
#+BEGIN_SRC c
static int gestvm_compile(lua_State *L);
#+END_SRC

#+NAME: funcs
#+BEGIN_SRC c
int
uxnasm_compile(const char *input,
               size_t ilen,
               int symtab,
               unsigned char **output,
               size_t *olen);

static int gestvm_compile(lua_State *L)
{
    lil_t lil;
    const char *membuf_name;
    const char *tal;
    gestvm_membuf *mem;
    void *ptr;
    sk_core *core;
    int rc;

    lua_getglobal(L, "__lil");
    lil = lua_touserdata(L, -1);

    core = lil_get_data(lil);

    membuf_name = lua_tostring(L, 1);
    tal = lua_tostring(L, 2);

    mem = NULL;
    ptr = NULL;
    rc = sk_core_lookup(core,
                        membuf_name,
                        strlen(membuf_name),
                        &ptr);

    mem = ptr;
    if (mem == NULL || rc ) {
        luaL_error(L, "Could not find %s\n", membuf_name);
        return 0;
    }

    if (mem->buf != NULL) {
        free(mem->buf);
        mem->buf = NULL;
    }

    rc = uxnasm_compile(tal,
                        strlen(tal),
                        1,
                        &mem->buf,
                        &mem->size);

    if (rc) {
        luaL_error(L, "uxnasm error");
    }

    return 0;
}
#+END_SRC
* copying into uxn VM (LIL: gmemcpy)
This looks up the memory buffer instance and copies it
over to the Uxn VM main memory.

Copy from source to destination.

#+NAME: lil_entries
#+BEGIN_SRC: c
lil_register(lil, "gmemcpy", l_gmemcpy);
#+END_SRC

#+NAME: static_funcdefs
#+BEGIN_SRC c
static lil_value_t l_gmemcpy(lil_t lil,
                             size_t argc,
                             lil_value_t *argv);
#+END_SRC

#+NAME: funcs
#+BEGIN_SRC c
static lil_value_t l_gmemcpy(lil_t lil,
                             size_t argc,
                             lil_value_t *argv)
{
    int rc;
    gestvm_membuf *mem;
    gestvm_uxn *gu;
    void *ud;
    sk_core *core;

    SKLIL_ARITY_CHECK(lil, "gmemload", argc, 2);

    core = lil_get_data(lil);

    rc = sk_core_generic_pop(core, &ud);
    SKLIL_ERROR_CHECK(lil, rc, "could not get memory");
    gu = ud;

    rc = sk_core_generic_pop(core, &ud);
    SKLIL_ERROR_CHECK(lil, rc, "could not get memory");
    mem = ud;

    rc = load(gu, mem);

    SKLIL_ERROR_CHECK(lil, rc, "could not copy.");

    return NULL;
}
#+END_SRC

#+NAME: static_funcdefs
#+BEGIN_SRC c
static int load(gestvm_uxn *gu, gestvm_membuf *rom);
#+END_SRC

#+NAME: funcs
#+BEGIN_SRC c
static int load(gestvm_uxn *gu, gestvm_membuf *rom)
{
    Uxn *u;
    char sym[3];
    int pos;

    sym[0] = sym[1] = sym[2] = 0;

    pos = 0;
    not_fread(sym, 3, rom, &pos);

    if (sym[0] == 'S' && sym[1] == 'Y' && sym[2] == 'M') {
        unsigned char b[2];
        unsigned short sz;
        b[0] = b[1] = 0;
        not_fread(b, 2, rom, &pos);
        sz = b[0] | (b[1] << 8);
        pos += sz;

    } else pos = 0;

    /* TODO: create getters for gestvm */

    u = &gu->u;

	not_fread(u->ram.dat + PAGE_PROGRAM,
              sizeof(u->ram.dat) - PAGE_PROGRAM,
                  rom,
                  &pos);
	return 0;
}
#+END_SRC
* GestVM Get Last Values (via Lua)
(At the time of writing, there was really no place to put
this. Memops already had a entry point for gestvm stuff,
so good enough).

Given an instance of GestVM (call =gestvmlast= from LIL
and then =pop()= it from Lua), return the state of
the current, next, and interpolation values.

#+NAME: static_funcdefs
#+BEGIN_SRC c
static int gestvm_last_values(lua_State *L);
#+END_SRC

#+NAME: funcs
#+BEGIN_SRC c
static int gestvm_last_values(lua_State *L)
{
    gestvm *gvm;
    SKFLT x, y, a;
    gvm = lua_touserdata(L, 1);
    x = y = a = 0.0;
    gestvm_get_last_values(gvm, &x, &y, &a);
    lua_pushnumber(L, x);
    lua_pushnumber(L, y);
    lua_pushnumber(L, a);
    return 3;
}
#+END_SRC
